{% set name = "mtuq" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/mtuqorg/mtuq.git
  git_rev: master


build:
  script: |
    {{ PYTHON }} -m pip install git+https://github.com/rmodrak/instaseis.git --no-deps -vv
    {{ PYTHON }} -m pip install . --no-deps -vv
  skip: false  # [win]  # adjust depending on platform support

requirements:
  host:
    - python =3
    - pip
    - numpy
    - scipy
    - obspy
    - pandas
    - xarray
    - netcdf4
    - h5py
    - mpi4py
    - retry
    - flake8
    - nose
    - pytest
    - compilers
  run:
    - python =3
    - numpy
    - scipy
    - obspy
    - pandas
    - xarray
    - netcdf4
    - h5py
    - mpi4py
    - retry
    - pytables

test:
  imports:
    - obspy
    - pandas
    - xarray
    - h5py
    - mtuq  # replace with your actual top-level import

about:
  home: https://github.com/mtuqorg/mtuq
  license:  BSD
  license_family:  BSD
  license_file: LICENSE
  summary: "MTUQ: Moment Tensor Uncertainty Quantification"
  description: |
    MTUQ provides tools for moment tensor inversion and uncertainty quantification using synthetic seismograms.
  doc_url: https://mtuq.readthedocs.io/ of what the package does.

extra:
  recipe-maintainers:
    - rwalkerlewis
